server:
  port: 8080

spring:
  # PostgreSQL datasource (commented)
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/alumni_db
  #   username: your_username_here
  #   password: your_password_here

  # H2 in-memory datasource for testing
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # auto create/update tables
    show-sql: true       # prints SQL in console
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
